### PR TITLE
Add `p-every` module

### PR DESCRIPTION
**Pull request by kevva**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm not sure about this one. I deliberately didn't make anything that wouldn't benefit from being custom made, meaning things that are run after all the promises are resolved. Here you could simply do the following instead:

```js
(await Promise.all([1, 2, 3])).every(x => typeof x === 'number')
```

Thoughts?

**Comment by kevva** [comment]
`Array.every` doesn't take a Promise as testing function though. I mainly created it to be used here for example https://github.com/kevva/github-remove-forks/blob/is-useless/index.js#L37.

**Comment by sindresorhus** [comment]
Ok, so I didn't see the point yesterday, since neither the `p-every` code nor https://github.com/kevva/github-remove-forks/blob/is-useless/index.js#L37 takes advantage of the fact that you need every test to return true, which means you could end it early if that's not the case.

Can you make it return false right away when the `testingFunction` returns false instead of at the end? Then it makes more sense as a module. You could probably use `p-map` and throw as custom error if a check returns `false`, then check for that in the catch handler. That way you'll get a `concurrency` option for free too.

**Comment by kevva** [comment]
Great idea! Added it in https://github.com/kevva/p-every/commit/25f8bd9bc9b656384ed165e73c011d5d66e6871d.

**Pull request merged**
